# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

properties = [
    { :number => 443, :square_feet => 1557, :lanai => 380, :floors => 3, :view=> "Marina/Canal, Sunrise",  :frontage=> "Marina", :full_address => "443 Opihikao Place 171" },
    { :number => 347, :square_feet => 1250, :lanai => 420, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina", :full_address => "347 Opihikao Place 411" },
    { :number => 217, :square_feet => 1518, :lanai => 210, :floors => 3, :view=> "Garden",                 :frontage=> "Other",  :full_address => "217 Opihikao Way 217" },
    { :number => 318, :square_feet => 1582, :lanai => 0,   :floors => 3, :view=> "Mountain",               :frontage=> "Other",  :full_address => "318 Opihikao Place 611" },
    { :number => 120, :square_feet => 1382, :lanai => 380, :floors => 3, :view=> "Marina/Canal",           :frontage=> "Marina", :full_address => "120 Opihikao Way 1032" },
    { :number => 347, :square_feet => 1250, :lanai => 300, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina", :full_address => "347 Opihikao Place 411" },
    { :number => 354, :square_feet => 1382, :lanai => 380, :floors => 3, :view=> "Garden",                 :frontage=> "Other",  :full_address => "354 Opihikao Place 541" },
    { :number => 212, :square_feet => 1164, :lanai => 400, :floors => 3, :view=> "Marina/Canal",           :frontage=> "Marina, Waterfront", :full_address => "212 Opihikao Way 852" },
    { :number => 505, :square_feet => 1250, :lanai => 420, :floors => 3, :view=> "Marina/Canal",           :frontage=> "Marina", :full_address => "505 Opihikao Place 12" },
    { :number => 312, :square_feet => 1718, :lanai => 0,   :floors => 3, :view=> "Garden, Mountain",       :frontage=> "Other",  :full_address => "312 Opihikao Place 632" },
    { :number => 168, :square_feet => 1164, :lanai => 364, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina", :full_address => "168 Opihikao Way 951" },
    { :number => 282, :square_feet => 1404, :lanai => 80,  :floors => 3, :view=> "None",                   :frontage=> "Other",  :full_address => "282 Opihikao Way 672" },
    { :number => 311, :square_feet => 1518, :lanai => 240, :floors => 3, :view=> "Marina/Canal",           :frontage=> "Marina, Waterfront", :full_address => "311 Opihikao Place 311" },
    { :number => 233, :square_feet => 1518, :lanai => 0,   :floors => 3, :view=> "None",                   :frontage=> "Other",  :full_address => "233 Opihikao Way 1091" },
    { :number => 199, :square_feet => 1518, :lanai => 400, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Other",  :full_address => "199 Opihikao Way 1162" },
    { :number => 410, :square_feet => 1518, :lanai => 400, :floors => 3, :view=> "None, Mountain",         :frontage=> "Other",  :full_address => "410 Opihikao Place 501" },
    { :number => 210, :square_feet => 1164, :lanai => 250, :floors => 3, :view=> "Diamond Head, Marina/Canal, Mountain, Sunset", :frontage=> "Marina, Waterfront", :full_address => "210 Opihikao Way 210" },
    { :number => 234, :square_feet => 1164, :lanai => 400, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina, Stream/Canal, Waterfront", :full_address => "234 Opihikao Way 791" },
    { :number => 425, :square_feet => 1250, :lanai => 160, :floors => 3, :view=> "Marina/Canal, Mountain, Sunrise", :frontage=>	"Marina, Waterfront", :full_address => "425 Opihikao Place 425" },
    { :number => 440, :square_feet => 1518, :lanai => 510, :floors => 3, :view=> "Garden",                 :frontage=> "Other",  :full_address => "440 Opihikao Place 572" },
    { :number => 114, :square_feet => 1164, :lanai => 400, :floors => 3, :view=> "Garden, Marina/Canal, Mountain, Sunrise", :frontage=>	"Marina, Waterfront", :full_address => "114 Opihikao Way 1041" },
    { :number => 264, :square_feet => 1518, :lanai => 0,   :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina, Waterfront", :full_address => "264 Opihikao Way 722" },
    { :number => 365, :square_feet => 1518, :lanai => 294, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina", :full_address => "365 Opihikao Place 365" },
    { :number => 318, :square_feet => 1502, :lanai => 240, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Other",  :full_address => "318 Opihikao Place 611" },
    { :number => 311, :square_feet => 1518, :lanai => 400, :floors => 3, :view=> "Marina/Canal, Mountain, Sunset", :frontage=> "Marina, Waterfront", :full_address => "311 Opihikao Place 311" },
    { :number => 465, :square_feet => 1164, :lanai => 400, :floors => 3, :view=> "Marina/Canal",           :frontage=> "Marina, Waterfront", :full_address => "465 Opihikao Place 112" },
    { :number => 229, :square_feet => 1757, :lanai => 0,   :floors => 3, :view=> "None",                   :frontage=> "Other",  :full_address => "229 Opihikao Way 1101" },
    { :number => 244, :square_feet => 1518, :lanai => 400, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina, Waterfront", :full_address => "244 Opihikao Way 772" },
    { :number => 425, :square_feet => 1250, :lanai => 420, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina, Stream/Canal, Waterfront", :full_address => "425 Opihikao Place 212" },
    { :number => 363, :square_feet => 1382, :lanai => 0,   :floors => 3, :view=> "Marina/Canal, Sunset",   :frontage=> "Marina", :full_address => "363 Opihikao Place 371" },
    { :number => 367, :square_feet => 1762, :lanai => 156, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina", :full_address => "367 Opihikao Place 361" },
    { :number => 206, :square_feet => 1518, :lanai => 400, :floors => 3, :view=> "City, Diamond Head, Marina/Canal, Mountain, Sunset", :frontage=> "Marina, Waterfront", :full_address => "206 Opihikao Way 861" },
    { :number => 108, :square_feet => 1518, :lanai => 250, :floors => 3, :view=> "Marina/Canal"	,          :frontage=> "Marina, Waterfront", :full_address => "108 Opihikao Way 1062" },
    { :number => 260, :square_feet => 1518, :lanai => 200, :floors => 3, :view=> "Marina/Canal"	,          :frontage=> "Marina", :full_address => "260 Opihikao Way 732" },
    { :number => 365, :square_feet => 1718, :lanai => 250, :floors => 3, :view=> "Marina/Canal, Mountain, Sunset", :frontage=> "Marina", :full_address => "365 Opihikao Place 362" },
    { :number => 315, :square_feet => 1557, :lanai => 380, :floors => 3, :view=> "Marina/Canal",           :frontage=> "Marina", :full_address => "315 Opihikao Place 441" },
    { :number => 443, :square_feet => 1557, :lanai => 380, :floors => 3, :view=> "Marina/Canal, Sunrise",  :frontage=> "Marina", :full_address => "443 Opihikao Place 171" },
    { :number => 347, :square_feet => 1250, :lanai => 420, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina", :full_address => "347 Opihikao Place 411" },
    { :number => 234, :square_feet => 1164, :lanai => 400, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina, Stream/Canal, Waterfront", :full_address => "234 Opihikao Way 791" },
    { :number => 440, :square_feet => 1518, :lanai => 510, :floors => 3, :view=> "Garden",                 :frontage=> "Other",  :full_address => "440 Opihikao Place 572" },
    { :number => 114, :square_feet => 1164, :lanai => 400, :floors => 3, :view=> "Garden, Marina/Canal, Mountain, Sunrise", :frontage=>	"Marina, Waterfront", :full_address => "114 Opihikao Way 1041" },
    { :number => 264, :square_feet => 1518, :lanai => 0,   :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina, Waterfront", :full_address => "264 Opihikao Way 722" },
    { :number => 365, :square_feet => 1518, :lanai => 294, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina", :full_address => "365 Opihikao Place 365" },
    { :number => 318, :square_feet => 1502, :lanai => 240, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "???",    :full_address => "318 Opihikao Place 611" },
    { :number => 311, :square_feet => 1518, :lanai => 400, :floors => 3, :view=> "Marina/Canal, Mountain, Sunset", :frontage=> "Marina, Waterfront", :full_address => "311 Opihikao Place 311" },
    { :number => 465, :square_feet => 1164, :lanai => 400, :floors => 3, :view=> "Marina/Canal",           :frontage=> "Marina, Waterfront", :full_address => "465 Opihikao Place 112" },
    { :number => 229, :square_feet => 1757, :lanai => 0,   :floors => 3, :view=> "None",                   :frontage=> "Other",  :full_address => "229 Opihikao Way 1101" },
    { :number => 385, :square_feet => 1518, :lanai => 400, :floors => 3, :view=> "Marina/Canal, Ocean, Sunrise, Sunset", :frontage=> "Marina, Waterfront", :full_address => "385 Opihikao Place 312" },
    { :number => 310, :square_feet => 1518, :lanai => 400, :floors => 3, :view=> "Mountain",               :frontage=> "Other",  :full_address => "310 Opihikao Place 631" },
    { :number => 315, :square_feet => 1557, :lanai => 380, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina, Stream/Canal, Waterfront",:full_address => "315 Opihikao Place 315"},
    { :number => 104, :square_feet => 1382, :lanai => 380, :floors => 3, :view=> "Marina/Canal, Ocean, Sunrise", :frontage=> "Marina, Waterfront", :full_address => "104 Opihikao Way 1072"},
    { :number => 216, :square_feet => 1164, :lanai => 400, :floors => 3, :view=> "Marina/Canal, Sunset",   :frontage=> "Marina, Waterfront", :full_address => "216 OPIHIKAO Way B842"},
    { :number => 176, :square_feet => 1518, :lanai => 0,   :floors => 3, :view=> "Marina/Canal, Ocean",    :frontage=> "Marina, Stream/Canal, Waterfront", :full_address => "176 Opihikao Way 931"},
    { :number => 363, :square_feet => 1382, :lanai => 380, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina", :full_address => "363 Opihikao Place 371"},
    { :number => 440, :square_feet => 1518, :lanai => 510, :floors => 3, :view=> "Garden, Mountain, Ocean", :frontage=>	"Other", :full_address => "440 Opihikao Place 572"},
    { :number => 142, :square_feet => 1518, :lanai => 400, :floors => 3, :view=> "Marina/Canal, Ocean, Sunrise", :frontage=> "Marina", :full_address => "142 Opihikao Way 982"},
    { :number => 343, :square_feet => 1250, :lanai => 420, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina", :full_address => "343 Opihikao Place 421"},
    { :number => 425, :square_feet => 1250, :lanai => 420, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina", :full_address => "425 Opihikao Place 212"},
    { :number => 341, :square_feet => 1250, :lanai => 240, :floors => 3, :view=> "Garden, Marina/Canal, Mountain, Sunset", :frontage=> "Marina, Waterfront", :full_address => "341 Opihikao Place 422"},
    { :number => 410, :square_feet => 1518, :lanai => 440, :floors => 3, :view=> "Mountain",               :frontage=> "Preservation", :full_address => "410 Opihikao Place 410"},
    { :number => 385, :square_feet => 1518, :lanai => 240, :floors => 3, :view=> "Marina/Canal, Mountain, Sunset", :frontage=> "Marina", :full_address => "385 Opihikao Place 312"},
    { :number => 108, :square_feet => 1518, :lanai => 0,   :floors => 3, :view=> "Marina/Canal",           :frontage=> "Marina, Waterfront", :full_address => "108 Opihikao Way 1062"},
    { :number => 230, :square_feet => 1518, :lanai => 400, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina", :full_address => "230 Opihikao Way 801"},
    { :number => 280, :square_feet => 1625, :lanai => 204, :floors => 3, :view=> "Marina/Canal, Sunset",   :frontage=> "Marina", :full_address => "280 Opihikao Way 681"},
    { :number => 349, :square_feet => 1518, :lanai => 0,   :floors => 3, :view=> "Marina/Canal, Sunset",   :frontage=> "Marina", :full_address => "349 Opihikao Place 402"},
    { :number => 409, :square_feet => 1518, :lanai => 0,   :floors => 3, :view=> "Marina/Canal, Mountain, Sunrise", :frontage=> "Marina", :full_address => "409 Opihikao Place 252"},
    { :number => 228, :square_feet => 1250, :lanai => 250, :floors => 3, :view=> "Diamond Head, Sunset",   :frontage=> "Marina, Waterfront", :full_address => "228 Opihikao Way 812"},
    { :number => 301, :square_feet => 1164, :lanai => 400, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina", :full_address => "301 Opihikao Place 472"},
    { :number => 150, :square_feet => 1518, :lanai => 400, :floors => 3, :view=> "Marina/Canal",           :frontage=> "Marina", :full_address => "150 Opihikao Way 962"},
    { :number => 120, :square_feet => 1382, :lanai => 380, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina", :full_address => "120 Opihikao Way 1032"},
    { :number => 206, :square_feet => 1518, :lanai => 240, :floors => 3, :view=> "Marina/Canal, Sunset",   :frontage=> "Marina, Stream/Canal, Waterfront", :full_address => "206 Opihikao Way 861"},
    { :number => 401, :square_feet => 1518, :lanai => 400, :floors => 3, :view=> "Marina/Canal, Mountain, Sunrise", :frontage=>	"Marina", :full_address => "401 Opihikao Place 272"},
    { :number => 497, :square_feet => 1762, :lanai => 0,   :floors => 3, :view=> "Marina/Canal",           :frontage=> "Marina", :full_address => "497 Opihikao Place 32"},
    { :number => 439, :square_feet => 1382, :lanai => 380, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina, Stream/Canal, Waterfront", :full_address => "439 Opihikao Place 181"},
    { :number => 377, :square_feet => 1164, :lanai => 400, :floors => 3, :view=> "Marina/Canal, Sunset",   :frontage=> "Marina", :full_address => "377 Opihikao Place 332"},
    { :number => 244, :square_feet => 1518, :lanai => 400, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina, Waterfront", :full_address => "244 Opihikao Way 772"},
    { :number => 425, :square_feet => 1250, :lanai => 420, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina, Stream/Canal, Waterfront", :full_address => "425 Opihikao Place 212"},
    { :number => 363, :square_feet => 1382, :lanai => 0,   :floors => 3, :view=> "Marina/Canal, Sunset",   :frontage=> "Marina", :full_address => "363 Opihikao Place 371"},
    { :number => 367, :square_feet => 1762, :lanai => 156, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina", :full_address => "367 Opihikao Place 361"},
    { :number => 206, :square_feet => 1518, :lanai => 400, :floors => 3, :view=> "City, Diamond Head, Marina/Canal, Mountain, Sunset", :frontage=> "Marina, Waterfront", :full_address => "206 Opihikao Way 861"},
    { :number => 108, :square_feet => 1518, :lanai => 250, :floors => 3, :view=> "Marina/Canal",           :frontage=> "Marina, Waterfront", :full_address => "108 Opihikao Way 1062"},
    { :number => 260, :square_feet => 1518, :lanai => 200, :floors => 3, :view=> "Marina/Canal",           :frontage=> "Marina", :full_address => "	260 Opihikao Way 732"},
    { :number => 365, :square_feet => 1718, :lanai => 250, :floors => 3, :view=> "Marina/Canal, Mountain, Sunset", :frontage=> "Marina", :full_address => "365 Opihikao Place 362"},
    { :number => 315, :square_feet => 1557, :lanai => 380, :floors => 3, :view=> "Marina/Canal	Marina",   :frontage=> "Marina", :full_address => "315 Opihikao Place 441"},
    { :number => 138, :square_feet => 1557, :lanai => 380, :floors => 3, :view=> "Marina/Canal, Mountain", :frontage=> "Marina", :full_address => "138 Opihikao Way 992"}
    
]
 

properties.each { |p|
    Property.create( :number => p[:number], :square_feet =>p[:square_feet],
        :lanai => p[:lanai], :floors => p[:floors], :view => p[:view], :frontage => p[:frontage],
        :full_address => p[:full_address])
    puts "#{p[:number]} #{p[:square_feet]}"
}
